# Generated by Django 3.1.2 on 2021-05-19 16:34

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='John', max_length=20, verbose_name='First name')),
                ('surname', models.CharField(help_text='Smith', max_length=20, verbose_name='Last name')),
                ('birth_date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Birth date')),
                ('photo', models.ImageField(null=True, upload_to=catalog.models.athlete_path, verbose_name='Photo')),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman')], default='man', help_text='Select a gender', max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Official name')),
                ('abbreviation', models.CharField(max_length=3, verbose_name='Official abbreviation')),
                ('flag', models.ImageField(upload_to=catalog.models.flag_path, verbose_name='Flag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Official name of the discipline')),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman')], default='man', help_text='Select a gender', max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Official name')),
                ('date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('athlete', models.ManyToManyField(help_text='Select athletes participating on this race', to='catalog.Athlete')),
                ('discipline', models.ManyToManyField(help_text='Select a discipline the athlete is doing', to='catalog.Discipline')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.country'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='discipline',
            field=models.ManyToManyField(help_text='Select a discipline the athlete is doing', to='catalog.Discipline'),
        ),
    ]
